name: generativeworld
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3

dev_dependencies:
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4